RuntimeType: Container
ServiceType: private
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: hanans426/one-api
DockerComposeEnvPath: .env.example
RegionId: cn-hangzhou
CustomParameters: ''
DockerComposeYamlPath: docker-compose.yml
Owner: hanans426
Branch: main
Platform: github
